# version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: neurolock-mysql
    command: ["--default-authentication-plugin=caching_sha2_password"]
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: neurolock
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
    ports:
      - "3307:3306"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer:4
    container_name: neurolock-adminer
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql-data:
